[tool.poetry]
name = "intermodel"
version = "0.0.34"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
openai = "*"
httpx = "*"
banana-dev = "*"
anthropic = "*"
tiktoken = "*"
python-dotenv = "*"
replicate = "*"
asgiref = "*"
tenacity = "*"
tokenizers = "*"


[tool.poetry.group.dev.dependencies]
black = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
