[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "intermodel"
version = "0.0.14"
dependencies = [
    "openai",
    "httpx",
    "banana-dev",
    "anthropic",
    "tiktoken",
    "python-dotenv"
]
